name: code-breakfast
channels:
- conda-forge
- defaults
dependencies:
- graphviz=2.38.0
- h5py=2.7.1
- jupyter=1.0.0
- matplotlib=2.1.1
- nb_conda=2.2.1
- numpy=1.13.3
- pandas=0.22.0
- pip=9.0.1
- pydot=1.2.3
- scikit-learn=0.19.1
- scipy=1.0.0
- seaborn=0.8.1
- pip:
  - keras==2.1.2
  - tensorflow==1.4.1
